# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87c7a3a090d1f499c6246edea17321233ead51686a4d814451e903f232c09505e08ac83bf67b41d884eb1146e572794d1871fa1abe8bef9a0544c78b40989917

test:
  secret_key_base: cea6bf7a7e2ba930897c4b58cff4a8c7a6ef01842d702eea983c73196c0217b7576556ab5e35a934331ecfdf2a953e2ab64479991ab7c904e4713aa2109d8928

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
